[package]
name = "scgld"
version = "0.3.0"
edition = "2021"
authors = ["Miranquil <miranquil@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.3", features = ["derive"] }
